name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils:
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.2
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0
  speech_to_text: ^7.0.0


  # FIREBASE
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  firebase_pagination: ^4.0.2

  # FIREBASE MESSAGING
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

  # STATE MANAGEMENT
  mobx: ^2.3.3
  flutter_mobx: ^2.2.1
  flutter_bloc: ^8.1.6
  animated_snack_bar: ^0.4.0

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.10

  # IMAGE
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  lottie: ^3.1.2

  # OTHER
  country_picker: ^2.0.26
  flutter_custom_tabs: ^2.1.0
  permission_handler: ^11.3.1
  flutter_html: ^3.0.0-beta.2
  path_provider: ^2.1.4
  playx_version_update: ^1.0.0
  webview_flutter: ^4.8.0
  file_picker: any

  # SOCIAL LOGIN
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main
  qr_flutter: ^4.1.0
  pix_flutter: ^2.2.0
  razorpay_flutter: ^1.3.7
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main
  flutter_stripe: ^11.1.0
  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main

  # MAP
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  crypto: ^3.0.6

  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.0.0
  share_plus: ^10.0.2
  app_links: ^6.3.2
  dotted_border: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/upi_payment/
    - assets/lottie/
    - assets/newDashboard/
    - assets/json/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
